### ISSUE TITLE
Translate all words

### ISSUE THREAD

**Issue by Kolenmi** [happy-se-life/kanban#1]
Please, can You translate **all** **words** into English?
This is a great plugin. 
Thank you for your work!

**Comment by happy-se-life** [comment]
Thank you for your comment.
I promise to translate all words into English.
Could you kindly wait for about a week.

**Comment by happy-se-life** [comment]
@Kolenmi 
Thank you for your comment.
I promise to translate all words into English.
Could you kindly wait for about a week.

**Comment by happy-se-life** [comment]
@Kolenmi 
I have translated all words into English.
I am glad if you can check it.

**Comment by Kolenmi** [comment]
Thank you, I will try soon.12:11, February 8, 2020, nomura <notifications@github.com>:@Kolenmi
I have translated all words into English.
I am glad if you can check it.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by Kolenmi** [comment]
Great work, thanks a lot!

**Comment by happy-se-life** [comment]
@Kolenmi 
You are welcome.
Any feedback is welcome.
