### ISSUE TITLE
Reguest: Show latest Recent History as first in list.

### ISSUE THREAD

**Issue by toshi808** [happy-se-life/kanban#12]
Please support that latest comment should be shown as first in Recent History.
It is helpful to know latest situation.

**Comment by happy-se-life** [comment]
@toshi808 
Hello,

I have enabled to select the display order of recent history and set DESC to default.
Check it out when you have the time.
Thanks,

**Comment by toshi808** [comment]
@happy-se-life 
Thank you very much. I have confirmed.
