### ISSUE TITLE
Don't ask on each state change for note (or make it optional)

### ISSUE THREAD

**Issue by yennor** [happy-se-life/kanban#14]
It's incredible annoying that on each status change of a ticket (dragging it aroudn) for a new note is asked. I always click cancel first, which also undoes the status change. Make asking for a note optional please :-)

**Comment by happy-se-life** [comment]
@yennor 
Hello,

I have made it optional. See constants.rb.
Please set DISPLAY_COMMENT_DIALOG_WHEN_DROP = 0.
Thanks,

**Comment by yennor** [comment]
works like a charm
