### ISSUE TITLE
assign by group

### ISSUE THREAD

**Issue by Kolenmi** [happy-se-life/kanban#2]
If the issue is assigned to your group and not to you, the kanban does not show a issue.
Kanban should show the issues assigned to group, and not only assigned to user.
Thank you.

**Comment by happy-se-life** [comment]
@Kolenmi 
Hi,
I have changed program to show the issues assigned to group.
Please check out.
Thanks,

**Comment by Kolenmi** [comment]
Thank you very much.16:50, February 29, 2020, nomura <notifications@github.com>:@Kolenmi
Hi,
I have changed program to show the issues assigned to group.
Please check out.
Thanks,

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile
