### ISSUE TITLE
Don't have the colors displayed on the board

### ISSUE THREAD

**Issue by sferg007** [happy-se-life/kanban#23]
Hello! I have Redmine versions 4.0.6.stable and Ruby 2.7.0-p0 versions and Rails 5.2.3. I installed your plugin, but I don't have the colors displayed on the board. And shorcuts dont work. The theme is standard. What can I do?

**Comment by happy-se-life** [comment]
@sferg007 
Hello! It is possible that javascript file and css file (kanban.js, kanban.css and hotkey.js) are not loaded correctly. Can you launch Chrome's developer tools and see if there are any error messages on the console?

**Comment by sferg007** [comment]
Hello! Thank you for your answer! I think you right, I found this entry in the redmine log file.
ActionController::RoutingError (No route matches [GET] "/plugin_assets/kanban/javascripts/jquery.floatThead.js")
But I don't now what to do with this :(

**Comment by happy-se-life** [comment]
@sferg007 
Hello, Can you enter the URL directly and see if the contents of the file are displayed?
Type this your browser. http://localhost:3000/plugin_assets/kanban/javascripts/jquery.floatThead.js
Here, "http://localhost:3000" is my pc's environment, pls. change this part to your env.
If the contents of the file are not displayed, pls. report error messages and full url string of kanban page to me. 
I expect this issue to be an installation issue, especially a URI configuration issue.
Best regards,

**Comment by sferg007** [comment]
Hello again! Thank you for your help!
I figured out how resolv this error!
I add in file
/etc/apache2/sites-enabled/001-redmine.conf
I added this:

    Alias "/plugin_assets/" /var/cache/redmine/default/plugin_assets/
    <Directory "/var/cache/redmine/default/plugin_assets">
        Allow from all
        Options -MultiViews
        Require all granted
    </Directory>
restart apache and it work now! Thank you!

**Comment by sferg007** [comment]
I close this issue
