### ISSUE TITLE
Doing my bit

### ISSUE THREAD

**Issue by aivorra** [happy-se-life/kanban#24]
Hi, great plugin!

I attach the "es.yml" if you want to add it. 

And I send you the "app/views/kanban/index.html.erb" with 3 little modification to improve the plugin.

Thanks for your work.

[files.zip](https://github.com/happy-se-life/kanban/files/6326301/files.zip)

**Comment by happy-se-life** [comment]
Hello,

Thank you for your cooperation.

It was very helpful because I was unaware of the problem you fixed.

I have committed to master.

Best regards,
