### ISSUE TITLE
Increase maximum WIP value

### ISSUE THREAD

**Issue by MikeFISys** [happy-se-life/kanban#30]
Hello! Thank you for this plugin.
Current maximal WIP limit is "4".
Is there any way to increase it?

**Comment by happy-se-life** [comment]
Hello!

It's currently hardcoded ...
plugins/kanban/app/views/kanban/index.html.erb
Line number is 142-147.
If you are in a hurry, please increase directly.
If you can wait for a while, I would like to modify it so that you can change the setting this weekend.

**Comment by MikeFISys** [comment]
Thanks a lot! 
That is more than enough!
