### ISSUE TITLE
Only display open versions in the filter dropdown

### ISSUE THREAD

**Issue by Timvde** [happy-se-life/kanban#31]
We have two week sprints, and the version filter dropdown is getting very long. It would be useful if the closed versions would be hidden. If there's a use case for the current behaviour, this could of course be a setting, or you could add an extra checkbox next to the dropdown to filter closed versions.

**Comment by happy-se-life** [comment]
I started on this task.

**Comment by happy-se-life** [comment]
Hello Tim,
I just committed this program fix.
I would be happy if you could check it.

**Comment by Timvde** [comment]
Sorry for the delay. It took some time before our operations team updated the version, and then I was on a holiday. It works great, thanks!

**Comment by happy-se-life** [comment]
Thank you for your reply. This ticket will be closed
