### ISSUE TITLE
Limit the view to certain type of trackers

### ISSUE THREAD

**Issue by EchedeyLR** [happy-se-life/kanban#39]
Currently, our instance uses several type of trackers, of which just 1 is classified as tasks, which are using with this extension.

However, the Kanvan view shows issues with all the type of trackers.

Is it possible to change this?

**Comment by happy-se-life** [comment]
Hi,

I started checking this issue.

**Comment by happy-se-life** [comment]
Hello,

Make sure that the filter when displaying kanban is the desired project name instead of "unspecified".
By the way, the tracker that can be used in the project is "Issue Tracking" in the project's "Settings". 
If you change your Tracker settings, old issues  will show the tracker from that time.

**Comment by EchedeyLR** [comment]
Thank you for the quick reply. I will try to explain better.

We have several type or trackers for issues: one being Bag Hours, other called Tasks, etc.

When I enable Kanban plugin, and even checking among the integrated filters, there is no way to set that I want to see just "Tasks", but I have to see all type of tracker for issues.

The idea was to integrate that possibility here.

Project filtering was not an issue because is not our use case.

**Comment by happy-se-life** [comment]
Hello,

Thank you for your detailed explanation.
Adding tracker filters isn't difficult, I'll try to work on it this weekend.

**Comment by happy-se-life** [comment]
Hi,

I'll let you know as soon as it's done.

**Comment by EchedeyLR** [comment]
So is this fixed already?

**Comment by happy-se-life** [comment]
Yes, It is already fixed.  Try master branch.

**Comment by EchedeyLR** [comment]
Thank you. I will test on Monday, but as you already fixed, I am closing this.
