### ISSUE TITLE
Add DE translation

### ISSUE THREAD

**Issue by HMT-HRO-MaMe** [happy-se-life/kanban#48]
Hi, if usefull I would like to contribute a german translation? Will do my best to do a good job but appreciate if any other German user would like to check my wording 😉

**Comment by happy-se-life** [comment]
Hi, I think it will be useful for many users, so please contribute. 
I would be happy if you could do that.

**Comment by happy-se-life** [comment]
Hi, 

It looks like good!  Thank you very much.
