### ISSUE TITLE
Problem not working with version 5

### ISSUE THREAD

**Issue by happy-se-life** [happy-se-life/kanban#54]

**Comment by happy-se-life** [comment]
Starting redmine seems to succeed.

<img width="491" alt="image" src="https://github.com/happy-se-life/kanban/assets/57052261/9d55546b-5397-4364-9cf4-e5c970d8bde1">

**Comment by happy-se-life** [comment]
Looking for bug information!

**Comment by sgorodskoi** [comment]
Work for me with 5.0.5

**Comment by happy-se-life** [comment]
It seems that there is no problem, so I will close this.
