### ISSUE TITLE
sub-project ticket

### ISSUE THREAD

**Issue by aij00** [happy-se-life/kanban#6]
試用させていただいています。
動作が軽快です。カンバンは、PMからするといろいろ機能を望んでしまいますが、チケットを直感的に割り振ることに特化していて使いやすいです。
機能追加としては、フィルターで、サブプロジェクトを含んだプロジェクトツリー全てのチケットが選択できるといいですね。

ちなみに動作環境は以下となります。
Environment:
  Redmine version                4.1.0.stable.19444
  Ruby version                   2.5.7-p206 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp

**Comment by happy-se-life** [comment]
@aij00 
Modification of the program has been finished.
It can show subproject issues when selecting parent project by filter.
Thank you for using!

**Comment by aij00** [comment]
動作の問題はありません。
ありがとうございました。
