### ISSUE TITLE
kanban link miss on menu 

### ISSUE THREAD

**Issue by camlafit** [happy-se-life/kanban#7]
Hello

Menu is missing when account is not a global administrator. 
An account as administrator project can enable plugin but any link are displayed. A direct access  with this account is working.

Follow screenshot on same project, with different account :

global Administrator account 
![Capture d’écran de 2020-04-14 14-42-43](https://user-images.githubusercontent.com/209915/79226288-66815900-7e5e-11ea-99aa-45adb8ed7321.png)

Administrator project :
![Capture d’écran de 2020-04-14 14-42-48](https://user-images.githubusercontent.com/209915/79226285-66815900-7e5e-11ea-969d-25cc8f9cd533.png)

https://redmine.tld/kanban?project_id=my-project is working with two accounts.

**Comment by happy-se-life** [comment]
@camlafit 
Hello,
I can not reproduce the problem.
Could you give me more detailed information. (redmine version, language, etc)
I am developing this plugin on redmine 3.4.9.
Best regards,

**Comment by happy-se-life** [comment]
@camlafit 
Hello,
Please check following setting of role.
Global header > Administration > Roles and permissions > select role (of an account as administrator project) > turn on checkbox of permission of kanban.
Best regards,

**Comment by camlafit** [comment]
Hello

yes was this :) I've enabled to each role the "kanban" permission. Menu link is enabled. But as direct link works could be nice to change permission name "Display menu link" 
Maybe could be interesting to enable it by default.

**Comment by happy-se-life** [comment]
@camlafit 
Hello

I'm glad the problem was solved.
I found a way to change permission name "Display menu link", but cannot enable it by default.
After the name was changed, it's permission of each roles was disabled (unchecked).
I'm worried if people who already have this plugin installed get confused.

**Comment by camlafit** [comment]
Hello

Sound a great news :) Maybe a simple notice on changelog could be enough. 
In more if people are yet think to manage permission to enable menu, after an update could be think again to check this part. Maybe :)

**Comment by happy-se-life** [comment]
@camlafit 
Hello

I have changed permission name and released new version. 
Thanks a lot.

**Comment by camlafit** [comment]
Hello

Great news. Role naming looks better. 
Indeed a role update must be required but looks normal as yet discussed :)
![Capture d’écran de 2020-05-18 12-47-41](https://user-images.githubusercontent.com/209915/82205069-42ee7a00-9906-11ea-9d11-1488c7b8fd39.png)
