### ISSUE TITLE
Fllter group and assignee are not limited to the current project 

### ISSUE THREAD

**Issue by camlafit** [happy-se-life/kanban#8]
Hello

On kanban page, sort option about assignee and group status take in consideration all group and account enable on redmine forge.
Should be restrict only to group/account set to the project.

Thanks :)

**Comment by happy-se-life** [comment]
@camlafit 
Hello. I know about this issue. I'll try to fix it next time.
I would be happy if you could wait for a while.

**Comment by camlafit** [comment]
Hello

Thanks a lot to take in consideration this issue :) No problem to wait and test next release

**Comment by happy-se-life** [comment]
@camlafit 
Hello

I have fixed the problem and released new version. 
Thanks a lot.

**Comment by camlafit** [comment]
Hello

Looks very nice :)
Miss an option "unspecified" in assigned list. It's also useful to see all assignations.

**Comment by happy-se-life** [comment]
@camlafit 
Hello

I have added an option "unspecified" in assigned list.
If you have time, I want you to check it.

**Comment by camlafit** [comment]
Hello

Thank a lot it's working as a charm. :)
