### ISSUE TITLE
Filter blank users

### ISSUE THREAD

**Issue by Smosia** [happy-se-life/kanban#9]
Hello, thank you for great plugin.

If I chose group with many users in filter many empty user rows appears in kanban table.
Could you please add option to skip users in kanban table with no cards(issues)?

I tried to do that by myself, but I don't know ruby language well.
You can add that option to constants.rb
Thank you

P.S. Maybe you can give some advices and I will try to do that?

**Comment by Smosia** [comment]
I've fix that problem, but I think you will do it in better way
https://github.com/Smosia/kanban/commit/0c4f4685e201790a7d2d7c2f5873817911102ba6

**Comment by happy-se-life** [comment]
@Smosia 
Hello,

I have added new option and released new version.
Please change DISPLAY_USER_WITHOUT_ISSUES = 0 in constants.rb.
I look forward to working with you.

**Comment by Smosia** [comment]
https://github.com/Smosia/kanban/commit/ed39b0e52a73e091fb2397226ea6b7177ff3f25e
Fix bug. Old implementation don't hide inactive users, because of: 
https://github.com/happy-se-life/kanban/blob/master/app/controllers/kanban_controller.rb#L69

Thank you for your work.
I've chose your kanban implementation to manage issues in team.

**Comment by happy-se-life** [comment]
@Smosia 
Hello,

That was my elementary mistake!!
Thank you for pointing out the bug.
